import styles from './order.module.css';
import Button from 'components/ui/button';
import OrderNavigation from 'components/order/navigation/order-navigation';
import Breadcrumbs from 'components/ui/breadcrumbs';
import useTranslation from 'next-translate/useTranslation';

function OrderStep2() {
  const { t } = useTranslation();
  const breadcrumbs = [
    {
      title: t('common:menu.home'),
      link: '/'
    },
    {
      title: t('common:menu.order process')
    }
  ];
  return (
    <section className={styles.orderContainer}>
      <div className={styles.breadcrumbsContainer}>
        <Breadcrumbs list={breadcrumbs} />
      </div>
      <OrderNavigation nextLink='/order/step-3?for=companies' />
      <p className={styles.orderContainer__intro}>
        {t('order:step2.main text 1')}
      </p>
      <div className={styles.orderContainer__messageContainer}>
        <p className={styles.orderContainer__message}>
          {t('order:step2.main text 2')}
        </p>
      </div>
      <div>
        <div className={styles.orderContainer__document}>
          <h2 className={styles.orderContainer__documentHeader}>
            CONTRACT FOR THE SALE OF POLYETHYLENE
          </h2>
          <h2 className={styles.orderContainer__documentHeader}>
            CONTRACT REF:
          </h2>
          <p className={styles.orderContainer__documentDate}>
            OCTOBER 26, 2020
          </p>
          <strong>1. SELLER</strong>
          <br />
          <br />
          INTEGRAL COMMODITIES S.A.
          <br />
          <br />
          VIA F. PELLI 13B, 6900 LUGANO, SWITZERLAND
          <br />
          <br />
          (HEREINAFTER REFERRED TO AS “SELLER”)
          <br />
          <br />
          <br />
          <br />
          <strong>2. BUYER</strong>
          <br />
          <br />
          (HEREINAFTER REFERRED TO AS "BUYER")
          <br />
          <br />
          <br />
          <br />
          <strong>3. PRODUCT</strong>
          <br />
          <br />
          HIGH DENSITY POLYETHYLENE, GRADE T60-475-119, PRODUCED BY KIYANLY
          PLANT OF “TURKMENGAS” STATE CONCERN (HEREINAFTER REFFERED TO AS
          “PRODUCT”). PRODUCT ORIGIN IS TURKMENISTAN. <br />
          <br />
          <br />
          <strong>4. QUALITY</strong>
          <br />
          <br />
          HIGH DENSITY POLYETHYLENE, GRADE T60-475-119 (TDS-1097-2018), AS
          USUALLY MADE AVAILABLE AT THE TIME AND PLACE OF LOADING.
          <br />
          <br />
          <br />
          <strong>5. QUAN TITY</strong>
          <br />
          <br />
          360 MT (+/- 10%) IN SELLER’S OPTION, ALWAYS AS PER BILL OF LADING
          ISSUED AT LOAD PORT, WITH POSSIBILITY TO INCREASE THE QUANTITY UPON
          MUTUAL AGREEMENT. <br />
          <br />
          <br />
          <strong>6. PACKING</strong>
          <br />
          <br />
          POLYETHYLENE SHOULD BE PACKED IN THE FIRM BAGS OF THE MANUFACTURER'S
          FACTORY WITH FULL INFORMATION PRINTED ON IT, NAME OF THE
          FACTORY-MANUFACTURER, WEIGHT OF THE NET, COUNTRY OF ORIGIN AND THE
          MARK OF POLYETHYLENE. <br />
          <br />
          <br />
          <strong>7. DELIVERY </strong>
          <br />
          <br />
          CFR NINGBO, CHINA (INCOTERMS 2020), IN CONTAINERS. PERIOD OF SHIPMENT
          IS WITHIN 10 (TEN) DAYS AFTER RECEIPT OF LETTER OF CREDIT BY SELLER’S
          ADVISING BANK. THE LATEST SHIPMENT DATE IS 10TH DECEMBER 2020. THE
          LOADING PORT IS MERSIN, TURKEY.
          <br />
          <br />
          <br />
          <strong>8. PRICE</strong>
          <br />
          <br />
          THE UNIT PRICE IS *** US DOLLARS PER METRIC TON, DUTY AND TAXES
          UNPAID. <br />
          <br />
          <br />
          <strong>9. PAYMENT</strong>
          <br />
          <br />
          9.1. PAYMENT FOR THE PRODUCT TO BE EFFECTED BY MEANS OF IRREVOCABLE
          DOCUMENTARY LETTEROF CREDIT AT SIGHT ISSUED TO SELLER`S ADVISING BANK
          COVERING THE 100% OF THE VALUE OF THE CONTRACT. ALL BANK CHARGES AND
          COMMISSIONS AT BENEFICIARY`S BANK ARE FOR BENEFICIARY`S ACCOUNT. ALL
          BANK CHARGES AND COMMISSIONS AT APPLICANT`S BANK ARE FOR APPLICANT`S
          ACCOUNT. LC CONFIRMATION COSTS TO BE ON APPLICANT’S ACCOUNT.
          <br />
          <br />
          AN IRREVOCABLE LETTER OF CREDIT TO BE ISSUED AS FOLLOWS:
          <br />
          <br />
          AMOUNT: USD <br />
          <br />
          VALIDITY: <br />
          <br />
          ADVISING BANK DETAILS:
          <br />
          <br />
          RAIFFEISEN BANK INTERNATIONAL AG
          <br />
          <br />
          AM STADTPARK 9, 1030 VIENNA, AUSTRIA
          <br />
          <br />
          SWIFT CODE: RZBAATWW
          <br />
          <br />
          <br />
          9.2. THE LETTER OF CREDIT TO BE PAYABLE AT SIGHT AGAINST PRESENTATION
          OF THE FOLLOWING DOCUMENTS:
          <br />
          <br />
          1. FINAL COMMERCIAL INVOICE IN 3 ORIGINALS AND 1 COPY ISSUED BY
          BENEFICIARY.
          <br />
          <br />
          2. 3/3 ORIGINAL OCEAN BILLS OF LADINGS, MADE OUT TO ORDER AND BLANK
          ENDORSED, MARKED ‘FREIGHT PREPAID’, NOTIFYING APPLICANT.
          <br />
          <br />
          3. PACKING LIST IN 3 ORIGINALS AND 1 COPY ISSUED BY BENEFICIARY
          INDICATING GROSS AND NET WEIGHTS.
          <br />
          <br />
          4. CERTIFICATE OF ANALYSIS ISSUED BY BENEFICIARY.
          <br />
          <br />
          5. CERTIFICATE OF ORIGIN ISSUED BY BENEFICIARY.
          <br />
          <br />
          <br />
          PERIOD FOR DOCUMENTS PRESENTATION:
          <br />
          <br />
          DOCUMENTS PRESENTED LATER THAN 30 DAYS AFTER BL DATE BUT DURING THE
          VALIDITY OF THE LC ARE ACCEPTABLE.
          <br />
          <br />
          <br />
          9.3. PAYMENTS FALLING DUE ON A SUNDAY OR MONDAY BANK HOLIDAY SHALL BE
          MADE ON THE FIRST BANKING DAY FOLLOWING. PAYMENTS FALLING DUE ON A
          SATURDAY OR ANY OTHER BANK HOLIDAY SHALL BE MADE ON THE LAST BANKING
          DAY PRIOR.
          <br />
          <br />
          <br />
          9.4. THE LETTER OF CREDIT TO BE ISSUED IN A FORM ACCEPTABLE TO SELLER
          AND SELLER’S BANK AT LEAST 5 BANKING DAYS PRIOR LOADING. IN THE EVENT
          THE LETTER OF CREDIT IS NOT RECEIVED IN A FULLY OPERATIVE FORM AS
          REQUIRED HEREIN THE SELLER SHALL HAVE THE RIGHT TO RECOVER ALL COSTS,
          DAMAGES, AND EXPENSES INCURRED BY THE SELLER AND TO DELAY LOADING AT
          SELLER’S DISCRETION UNTIL SUCH TIME THE ACCEPTABLE LETTER OF CREDIT
          IS RECEIVED.
          <br />
          <br />
          <br />
          <strong>10. DETERMINATION OF QUANTITY/QUALITY</strong>
          <br />
          <br />
          BILL OF LADING QUANTITY TO BE DETERMINED AS PER STANDARD PRACTICE AT
          LOAD PLACE. FINAL QUANTITY AT LOADING PLACE STATED AT BILL OF LADING.
          <br />
          <br />
          QUALITY TO BE DETERMINDED AS PER PLANT QUALITY PASSPORT ISSUED AT
          PLACE OF ORIGIN AND HAS TO BE BINDING AND FINAL.
          <br />
          <br />
          INSPECTION COSTS FOR QUANTITY AT THE PLACE OF DISCHARGE TO BE TO THE
          ACCOUNT OF THE BUYER. <br />
          <br />
          INSPECTION COSTS FOR QUANTITY AT THE LOADING PLACE TO BE TO THE
          ACCOUNT OF THE SELLER. <br />
          <br />
          ANY QUANTITY AND QUALITY CLAIMS TO BE RECEIVED BY SELLER WITHIN 10
          DAYS AFTER DISCHARGE. ANY CLAIMS RECEIVED AFTER SUCH TIME IS TO BE
          CONSIDERED AS TIME BARRED. THE QUANTITY CLAIMS FROM THE BUYER SHALL
          BE BACKED UP BY RELEVANT CERTIFICATES ISSUED BY FIRST CLASS
          INDEPENDENT INSPECTOR.
          <br />
          <br />
          <br />
          <strong>11. DEMURRAGE</strong>
          <br />
          <br />
          DEMURRAGE RATE AT PORT OF DISCHARGE AS PER TERMS AND CONDITIONS OF
          THE CARRIER. DEMURRAGE FREE TIME IS 14 DAYS AT DISPORT FOR DISCHARGE
          AND RETURN OF CONTAINERS TO SHIPPING LINE.
          <br />
          <br />
          DEMURRAGE IF ANY TO BE SUBMITTED TO BUYERS WITH SUPPORTING DOCS
          (DEMURRAGE CALCULATION AND SELLERES INVOICE) BY EMAIL. THE BUYER
          SHALL EXAMINE SUBMITTED DEMURRAGE CLAIMS AND RESPOND TO THE SELLER
          WITHIN 30 CALENDAR DAYS ON RECEIPT OF THE CLAIM. IF THE BUYER FAILS
          TO DISPUTE DEMURRAGE TIMEOUSLY, THE DEMURRAGE SHALL BECOME
          IMMEDIATELY DUE AND PAYABLE IN FULL TO THE SELLER. THE BUYER
          IRREVOCABLY WAIVES IN FULL ANY RIGHT TO DISPUTE ANY SUCH DEMURRAGE
          CLAIM FOLLOWING THE LAPSE OF THE PERMITTED TIME PERIOD, UNLESS SUCH
          WAIVER IS PROHIBITED BY THE APPLICABLE LAW.
          <br />
          <br />
          THE BUYER SHALL PAY THE DEMURRAGE DUE WITHIN 30 DAYS FROM THE DATE OF
          THE BUYER’S RESPONSE OR THE FINAL PERMITTED DAY OF RESPONSE IF NO
          RESPONSE IS FORTHCOMING. IN CASE OF DISPUTE BUYER TO PAY THE
          UNDISPUTED AMOUNT. THE DISPUTED AMOUNT TO BE SETTLED AMICABLY AND
          ULTIMATELY BY ARBITRATION IN LONDON.
          <br />
          <br />
          <br />
          <strong>12. ASSIGNMENT</strong>
          <br />
          <br />
          WITHOUT THE PRIOR WRITTEN CONSENT OF THE OTHER PARTY, WHICH CONSENT
          SHALL NOT BE UNREASONABLY WITHHELD, NEITHER PARTY MAY ASSIGN ITS
          RIGHTS OR OBLIGATIONS UNDER THIS AGREEMENT IN FULL OR IN PART, EXCEPT
          THAT THE SELLER AND ITS ASSIGNS MAY WITHOUT SUCH CONSENT ASSIGN ALL
          OR A PORTION OF THEIR RIGHTS TO RECEIVE AND OBTAIN PAYMENT UNDER THE
          CONTRACT IN CONNECTION WITH SECURITIZATION OR BANK FUNDING
          ARRANGEMENTS. ANY SUCH ASSIGNMENT WILL NOT DETRACT FROM THE SELLER'S
          OBLIGATIONS UNDER THIS CONTRACT.
          <br />
          <br />
          <br />
          <strong>13. RISK &amp; PROPERTY</strong>
          <br />
          <br />
          RISK AND TITLE OF THE PRODUCT DELIVERED UNDER THIS CONTRACT SHALL
          PASS FROM SELLER TO BUYER AS THE PRODUCT IS LOADED AT THE PLACE OF
          LOADING. THE SELLER SHALL HAVE THE OBLIGATION TO WARRANT THAT NO
          THIRD PARTY SHALL EXERCISE AGAINST THE BUYER ANY RIGHTS WITH RESPECT
          TO THE DELIVERED PRODUCT.
          <br />
          <br />
          <br />
          <strong>14. DESTINATION RESTRICTION</strong>
          <br />
          <br />
          THE BUYER SHALL NOT DIRECTLY OR INDIRECTLY BY ANY MEANS:
          <br />
          <br /> <br />
          (A) ON-SELL, SUPPLY OR DELIVER THE PRODUCT TO ANY PERSON OR ENTITY IN
          ANY RESTRICTED DESTINATION OR FOR THE PURPOSE OF ANY ACTIVITY CARRIED
          ON IN OR FROM ANY RESTRICTED DESTINATION, OR
          <br />
          <br />
          (B) IMPORT THE PRODUCT INTO ANY RESTRICTED DESTINATION.
          <br />
          <br /> <br />
          FOR THE PURPOSES OF THIS CLAUSE, AS STATED IN ITEM "(B)" ABOVE, THE
          “RESTRICTED DESTINATION” SHALL MEAN ANY DESTINATION TO WHICH SUPPLIES
          ARE PROHIBITED OR RESTRICTED BY THE LAWS PREVAILING IN THE PLACE OF
          ORIGIN OF THE PRODUCT AND/OR BY THE UNITED NATIONS/EUROPEAN UNION
          AND/OR BY THE UNITED STATES OF AMERICA AND/OR ANY OTHER AUTHORITY OR
          ORGANISATION HAVING JURISDICTION OVER THE SELLER OR THE BUYER.
          <br />
          <br /> <br />
          THE BUYER SHALL, UPON REQUEST FROM THE SELLER, PROMPTLY PROVIDE THE
          SELLER WITH DOCUMENTATION VERIFYING THE FINAL DESTINATION OF THE
          PRODUCT AS ON-SOLD BY THE BUYER.
          <br />
          <br /> <br />
          THE BUYER SHALL INDEMNIFY AND HOLD HARMLESS THE SELLER FOR ANY DIRECT
          LOSSES, COSTS, DAMAGES, FINES, AND / OR OTHER PENALTIES INCURRED BY
          OR IMPOSED UPON THE SELLER AS A RESULT OF ANY BREACH OF THIS CLAUSE.
          <br />
          <br /> <br />
          WITHOUT PREJUDICE TO THE FOREGOING AND TO ANY OF THE SELLER’S OTHER
          RIGHTS, THE SELLER MAY IMMEDIATELY TERMINATE THIS CONTRACT OR SUSPEND
          PERFORMANCE OF ANY OF ITS OBLIGATIONS UNDER THIS CONTRACT IF THE
          BUYER FAILS, OR THE SELLER HAS REASONABLE GROUNDS TO BELIEVE THAT THE
          BUYER WILL FAIL, TO COMPLY WITH THIS CLAUSE.
          <br />
          <br />
          <br />
          <strong>15. FORCE MAJEURE</strong>
          <br />
          <br />
          NEITHER BUYER NOR SELLER WILL BE LIABLE FOR DAMAGES OR OTHERWISE FOR
          ANY FAILURE OR DELAY IN PERFORMANCE OF ANY OBLIGATION UNDER THIS
          CONTRACT, OTHER THAN ANY OBLIGATION TO MAKE PAYMENT DUE UNDER THIS
          CONTRACT (INCLUDING DEMURRAGE), WHERE SUCH FAILURE OR DELAY IS CAUSED
          BY FORCE MAJEURE, BEING ANY EVENT OR OCCURRENCE OR CIRCUMSTANCE
          REASONABLY BEYOND THE CONTROL OF THAT PARTY, INCLUDING BUT WITHOUT
          PREJUDICE TO THE GENERALITY OF THE FOREGOING, FAILURE OR DELAY CAUSED
          BY OR RESULTING FROM ACTS OF GOD, STRIKES, FIRES, FLOODS, WARS,
          (WHETHER DECLARED OR UNDECLARED), RIOTS, DESTRUCTION OF THE PRODUCT,
          CLAIM OF A FORCE MAJOR EVENT BY THE SUPPLIER OR PRODUCER OF THE
          PRODUCT, LACK OF AVAILABILITY OF THE PRODUCT FROM THE PRIME SUPPLIER,
          PERILS OF THE SEA, EMBARGOES, ACCIDENTS, RESTRICTIONS IMPOSED BY ANY
          GOVERNMENT AUTHORITY OR PERSON PURPORTING TO ACT THEREFOR (INCLUDING
          ALLOCATIONS, PRIORITIES, REQUISITIONS, QUOTAS AND PRICE CONTROLS )
          DELAYS OF THE CARRYING VESSEL DUE TO BREAKDOWN, ADVERSE WEATHER OR
          SEA CONDITIONS.
          <br />
          <br />
          THE PARTY WHOSE PERFORMANCE IS SO AFFECTED SHALL NOTIFY THE OTHER
          PARTY HERETO INDICATING THE NATURE OF SUCH CAUSE AND, TO THE EXTENT
          POSSIBLE, INFORM THE OTHER PARTY OF THE EXPECTED DURATION OF THE
          FORCE MAJEURE EVENT.
          <br />
          <br />
          THE TIME FOR THE SELLER OR BUYER TO PERFORM THEIR RESPECTIVE
          OBLIGATIONS UNDER THE CONTRACT (OTHER THAN THE OBLIGATION TO PAY WHEN
          DUE ALL AMOUNTS THAT ARE OWING TO THE OTHER WHICH SHALL NOT BE
          SUSPENDED) SHALL BE EXTENDED DURING ANY PERIOD DURING WHICH THESE
          OBLIGATIONS ARE PREVENTED, HINDERED, CURTAILED OR DELAYED BY REASON
          OF ANY FORCE MAJEURE EVENT UP TO A PERIOD OF 30 CONSECUTIVE DAYS. IF
          ANY OF THESE OBLIGATIONS SHALL BE PREVENTED, HINDERED, CURTAILED OR
          DELAYED FOR MORE THAN 30 DAYS, EITHER PARTY MAY TERMINATE THIS
          CONTRACT WITH RESPECT TO SUCH DELIVERY UPON WRITTEN NOTICE TO THE
          OTHER PARTY.
          <br />
          <br />
          <br />
          <strong>COVID-19</strong>
          <br />
          <br /> 1. IF A PARTY (“COVID-19 AFFECTED PARTY”) IS PREVENTED,
          HINDERED OR DELAYED FROM PERFORMING IN WHOLE OR IN PART ANY
          OBLIGATION OF THIS CONTRACT BY REASON OF THE EFFECTS OF COVID-19
          WHETHER FORESEEABLE OR UNFORESEEABLE (“COVID-19 EVENT”), IT SHALL
          GIVE WRITTEN NOTICE TO THE OTHER PARTY PROMPTLY AND IN ANY EVENT
          WITHIN FIVE (5) CALENDAR DAYS OF THE OCCURRENCE (OR AFTER RECEIVING
          NOTICE OF THE OCCURRENCE) OF THE COVID-19 EVENT, GIVING, TO THE
          EXTENT REASONABLY PRACTICABLE, THE DETAILS AND EXPECTED DURATION OF
          THE COVID-19 EVENT AND THE EFFECTS, OR REASONABLY ANTICIPATED
          EFFECTS, ON ITS ABILITY TO PERFORM (THE “COVID-19 NOTICE”). DELAY OR
          FAILURE TO COMPLY WITH THE NOTICE PROVISIONS IN THIS CLAUSE SHALL NOT
          DEPRIVE THE COVID-19 AFFECTED PARTY OF THE RIGHT TO CLAIM RELIEF BUT
          SHALL EXPOSE THE COVID-19 AFFECTED PARTY TO LIABILITY IN DAMAGES TO
          THE OTHER PARTY FOR LOSS SUFFERED BY THE OTHER PARTY WHICH COULD HAVE
          BEEN AVOIDED BY PROMPT NOTICE. THE COVID-19 AFFECTED PARTY SHALL USE
          COMMERCIALLY REASONABLE EFFORTS TO OVERCOME THE EFFECTS OF THE
          COVID-19 EVENT.
          <br />
          <br /> <br />
          2. PROVIDED THAT A COVID-19 NOTICE HAS BEEN GIVEN AND THE COVID-19
          AFFECTED PARTY HAS USED AND IS CONTINUING TO USE COMMERCIALLY
          REASONABLE EFFORTS TO OVERCOME THE EFFECTS OF THE COVID-19 EVENT, FOR
          AS LONG AS THE COVID-19 EVENT AND/OR ITS EFFECTS EXISTS AND TO THE
          EXTENT THAT PERFORMANCE IS PREVENTED, HINDERED OR DELAYED BY THE
          COVID-19 EVENT AND/OR ITS EFFECTS, THE COVID-19 AFFECTED PARTY SHALL
          NOT BE LIABLE TO THE OTHER PARTY AND THE COVID-19 AFFECTED PARTY MAY
          SUSPEND PERFORMANCE OF ITS OBLIGATIONS UNDER THIS CONTRACT (A
          “COVID-19 SUSPENSION”). THE COVID-19 AFFECTED PARTY SHALL PROMPTLY
          NOTIFY THE OTHER PARTY WHEN THE COVID-19 EVENT AND/OR ITS EFFECTS
          HAVE CEASED OR BEEN OVERCOME.
          <br />
          <br /> <br />
          3. IF THE PERIOD OF THE COVID-19 SUSPENSION IS EQUAL TO OR EXCEEDS 30
          DAYS FROM THE DATE OF THE COVID-19 NOTICE, AND SO LONG AS THE
          COVID-19 EVENT IS CONTINUING, EITHER PARTY MAY, IN ITS SOLE
          DISCRETION AND BY WRITTEN NOTICE, (A) IF THE CONTRACT IS FOR A SINGLE
          DELIVERY, TERMINATE THIS CONTRACT OR (B) IF THE CONTRACT IS FOR
          MULTIPLE DELIVERIES, TERMINATE THE DELIVERIES AFFECTED BY THE
          COVID-19 EVENT. UPON TERMINATION IN ACCORDANCE WITH THIS CLAUSE,
          NEITHER PARTY SHALL HAVE ANY FURTHER LIABILITY TO THE OTHER PARTY IN
          RESPECT OF THIS CONTRACT OR, AS THE CASE MAY BE, THE TERMINATED
          DELIVERIES EXCEPT FOR ANY RIGHTS AND REMEDIES PREVIOUSLY ACCRUED
          UNDER THE CONTRACT INCLUDING ANY PAYMENT OR REPAYMENT OBLIGATIONS.
          <br />
          <br /> <br />
          4. A COVID-19 EVENT INCLUDES (BUT IS NOT LIMITED TO) THE FOLLOWING:
          <br />
          <br />
          A. CLOSING OF, OR RESTRICTIONS UPON THE USE OF MOORING FACILITIES,
          DOCKS, PORTS, HARBOURS, RAILROADS OR OTHER NAVIGATIONAL OR
          TRANSPORTATION MECHANISMS;
          <br />
          <br />
          B. SHORTAGES OF OR RESTRICTIONS ON LABOUR OR WORKFORCE;
          <br />
          <br />
          C. DETENTION OF THE PRODUCT AND/OR VESSEL;
          <br />
          <br />
          D. ANY ACT OF ANY GOVERNMENTAL AUTHORITY; AND
          <br />
          <br />
          E. GOOD FAITH COMPLIANCE WITH ANY LAW, REGULATION, ORDER, REQUEST OR
          DIRECTIVE OF ANY SUPRANATIONAL, INTERNATIONAL, NATIONAL, PORT,
          TRANSPORTATION, LOCAL OR OTHER AUTHORITY OR AGENCY.
          <br />
          <br />
          F. ANY UNANNOUNCED OR UNOFFICIAL GOVERNMENT ACTIONS HAVING EFFECT
          IDENTICAL OR SIMILAR TO THE ABOVE.
          <br />
          <br />
          5. A PARTY’S FAILURE TO PERFORM ITS OBLIGATIONS UNDER THIS CONTRACT
          DUE TO ECONOMIC OR FINANCIAL CONSIDERATIONS SHALL NOT CONSTITUTE A
          COVID-19 EVENT.
          <br />
          <br />
          6. IN THE EVENT THAT THE COVID-19 AFFECTED PARTY HAS RECEIVED A
          PREPAYMENT FROM THE OTHER PARTY AND WISHES TO RELY ON A COVID-19
          EVENT TO BE RELEASED FROM ITS DELIVERY OR OTHER OBLIGATIONS RELATING
          TO THE PREPAYMENT, THE COVID-19 AFFECTED PARTY SHALL IMMEDIATELY
          REFUND THE PREPAYMENT.
          <br />
          <br />
          <br />
          <strong>16. APPLICABLE LAW AND DISPUTE RESOLUTION</strong>
          <br />
          <br />
          THE PARTIES HERETO AGREE THAT THIS CONTRACT IN ITS ENTIRETY, ALL
          TRANSACTIONS EXECUTED HEREUNDER AND ALL RELATIONSHIPS BETWEEN THE
          PARTIES ARISING OUT OF OR IN CONNECTION HEREWITH SHALL BE CONSTRUED
          UNDER AND GOVERNED IN ALL RESPECTS BY THE LAWS OF ENGLAND AND WALES.{' '}
          <br />
          <br />
          ANY DISPUTES BETWEEN THE PARTIES ARISING OUT OF OR IN CONNECTION WITH
          THIS CONTRACT OR THE INTERPRETATION, BREACH OR ENFORCEMENT HEREOF
          SHALL BE SUBMITTED TO AND FINALLY SETTLED BY THE LONDON COURT OF
          INTERNATIONAL ARBITRATION (LCIA) IN ACCORDANCE WITH ITS ARBITRATION
          RULES IN FORCE ON THE DATE WHEN THE NOTICE OF ARBITRATION IS
          SUBMITTED IN ACCORDANCE WITH THESE RULES.
          <br />
          <br />
          THE NUMBER OF ARBITRATORS SHALL BE THREE, EACH PARTY BEING ENTITLED
          TO NOMINATE ONE. THE PRESIDING ARBITRATOR SHALL BE APPOINTED BY THE
          SO TWO CHOSEN. <br />
          <br />
          THE SEAT, OR LEGAL PLACE, OF ARBITRATION SHALL BE LONDON, ENGLAND.{' '}
          <br />
          <br />
          THE LANGUAGE TO BE USED IN THE ARBITRAL PROCEEDINGS SHALL BE ENGLISH.
          THE GOVERNING LAW OF THE CONTRACT SHALL BE THE SUBSTANTIVE LAW OF
          ENGLAND AND WALES.
          <br />
          <br />
          <br />
          <strong>17. CLAIMS </strong>
          <br />
          <br />
          IF ANY CLAIMS ARISE UNDER OR IN CONNECTION WITH THIS CONTRACT, THE
          CLAIMING PARTY SHALL NOTIFY THE OTHER PARTY OF ITS CLAIM IN WRITING
          WITHIN 30 DAYS FROM THE DATE OF THE COMPLETION OF FINAL DISCHARGE,
          FAILING WHICH THE CLAIM SHALL BE DEEMED WAIVED AND ABSOLUTELY BARRED.
          THIS CLAUSE SHALL NOT APPLY TO: CLAIMS IN RESPECT OF QUALITY AND / OR
          QUANTITY, WHICH ARE COVERED IN CLAUSE 10.
          <br />
          <br />
          <br />
          <strong>18. ENTIRE AGREEMENT</strong>
          <br />
          <br />
          THE CONTRACT CONTAINS THE ENTIRE AGREEMENT BETWEEN THE PARTIES AND
          SUPERSEDES ALL PREVIOUS NEGOTIATIONS, REPRESENTATIONS, AGREEMENTS OR
          COMMITMENTS WITH REGARD TO ITS SUBJECT MATTER. <br />
          <br />
          EACH PARTY ACKNOWLEDGES THAT IN ENTERING INTO THIS CONTRACT IT HAS
          NOT RELIED ON ANY REPRESENTATIONS, WARRANTIES, STATEMENTS OR
          UNDERTAKINGS EXCEPT THOSE WHICH ARE EXPRESSLY SET OUT HEREIN. <br />
          <br />
          EACH PARTY FURTHER ACKNOWLEDGES THAT IT WILL ONLY BE ENTITLED TO
          REMEDIES IN RESPECT OF BREACH OF THE EXPRESS TERMS OF THE CONTRACT
          AND WILL NOT BE LIABLE IN TORT OR UNDER ANY COLLATERAL CONTRACT OR
          WARRANTY IN RESPECT OF ANY REPRESENTATIONS, WARRANTIES, STATEMENTS OR
          UNDERTAKINGS WHICH MAY HAVE BEEN MADE PRIOR TO THE CONTRACT BEING
          ENTERED INTO. <br />
          <br />
          THIS CONTRACT IS NOT INTENDED TO GIVE ANY THIRD PARTY THE RIGHT TO
          ENFORCE ANY OF ITS TERMS.
          <br />
          <br />
          <br />
          <strong>19. THIRD PARTY RIGHTS </strong>
          <br />
          <br />
          NOTHING IN THIS AGREEMENT SHALL BE CONSIDERED OR CONSTRUED AS
          CONFERRING ANY RIGHT OR BENEFIT ON A PERSON NOT A PARTY TO THIS
          AGREEMENT AND THE PARTIES DO NOT INTEND THAT ANY TERM OF THIS
          AGREEMENT SHOULD BE ENFORCEABLE, BY VIRTUE OF THE CONTRACTS (RIGHTS
          OF THIRD PARTIES) ACT 1999, BY ANY PERSON WHO IS NOT A PARTY TO THIS
          AGREEMENT.
          <br />
          <br />
          <br />
          <strong>20. LIMITATION OF LIABILITY</strong>
          <br />
          <br />
          EXCEPT AS EXPRESSLY PROVIDED IN THIS CONTRACT, NEITHER SELLER NOR
          BUYER SHALL BE LIABLE FOR CONSEQUENTIAL, INDIRECT OR SPECIAL
          LOSSES/DAMAGES OF ANY KIND ARISING OUT OF OR IN ANY WAY CONNECTED
          WITH THE CONCLUSION, THE PERFORMANCE, THE FAILURE TO PERFORM OR THE
          TERMINATION OF THIS CONTRACT.
          <br />
          <br />
          <br />
          <strong>21. OTHER TERMS </strong>
          <br />
          <br />
          OTHERWISE AND WHERE NOT IN CONFLICT WITH THE FOREGOING, INCOTERMS
          2020 FOR CFR SALES TO APPLY.
          <br />
          <br />
          THE FOLLOWING SHALL NOT APPLY TO THIS AGREEMENT:
          <br />
          <br />
          THE UNIFORM LAW ON SALES AND THE UNIFORM LAW ON FORMATION TO WHICH
          EFFECT IS GIVEN BY THE UNIFORM LAWS ON INTERNATIONAL SALES ACT 1967
          <br />
          <br />
          THE UNITED NATIONS CONVENTION ON CONTRACTS FOR THE INTERNATIONAL SALE
          OF GOODS OF 1980
          <br />
          <br />
          THE UNITED NATIONS CONVENTION ON PRESCRIPTION (LIMITATION) IN THE
          INTERNATIONAL SALE OF GOODS OF 1974 AND THE AMENDING PROTOCOL OF 1980
          <br />
          <br />
          THE CONTRACTS (RIGHTS OF THIRD PARTIES) ACT 1999 <br />
          <br />
          <br />
          <strong>22. REPRESENTATIONS, WARRANTIES AND COVENANTS</strong>
          <br />
          <br />
          THE PARTIES HEREBY COVENANT AND REPRESENT AND WARRANT TO EACH OTHER,
          AND ACKNOWLEDGE AND CONFIRM THAT EACH PARTY MAY RELY ON FAITHFULNESS
          AND RELIABILITY OF SUCH COVENANTS, REPRESENTATIONS AND WARRANTIES IN
          CONNECTION WITH ENTERING INTO THIS AGREEMENT, THAT EACH PARTY IS AN
          ENTITY DULY ORGANIZED, VALIDLY EXISTING AND IN GOOD STANDING UNDER
          THE APPLICABLE LAWS OF ITS JURISDICTION AND THAT THE REPRESENTATIVES
          OF THE PARTIES HAVE NECESSARY POWERS AND STATUS TO DO SO ON BEHALF OF
          THE SELLER AND BUYER RESPECTIVELY.
          <br />
          <br />
          <br />
          <strong>23. INSURANCE</strong>
          <br />
          <br />
          TO BE COVERED BY BUYER AT THEIR OWN RISK AND COSTS, FROM THE MOMENT
          THE GOODS ARE LOADED AT LOADING PLACE UNTIL COMPLETION OF DISCHARGE.
          <br />
          <br />
          BUYER UNDERTAKES TO CONFIRM INSURANCE COVERAGE UPON FIRST REQUEST
          FROM SELLER BY FORWARDING A COPY OF THE INSURANCE POLICY TO SELLER.
          <br />
          <br />
          <br />
          <strong>24. SANCTIONS</strong>
          <br />
          <br />
          SHOULD ANY SANCTION, REGULATION, STATUTE, OFFICIAL EMBARGO MEASURES
          OR ANY ‘SPECIALLY DESIGNATED NATIONALS’ OR ‘BLOCKED PERSONS’ LISTS,
          OR ANY EQUIVALENT LISTS MAINTAINED AND IMPOSED BY THE UNITED NATIONS,
          THE EUROPEAN UNION, HER MAJESTY’S TREASURY IN THE UNITED KINGDOM, THE
          UNITED STATES DEPARTMENT OF TREASURY’S OFFICE OF FOREIGN ASSETS
          CONTROL, THE UNITED STATES STATE DEPARTMENT OR ANY REPLACEMENT OR
          OTHER REGULATORY BODY ENFORCING ECONOMIC AND TRADE SANCTIONS
          LEGISLATION IN APPLICABLE COUNTRIES OR BY ANY SUPRANATIONAL OR
          INTERNATIONAL GOVERNMENTAL ORGANIZATION PREVENT OR PROHIBIT
          PERFORMANCE OF EITHER PARTY’S OBLIGATIONS, THE AFFECTED PARTY SHALL
          BE ENTITLED TO UNILATERALLY TERMINATE THIS CONTRACT WITH A 5-DAY
          PRIOR WRITTEN NOTICE. AND WITH NO LIABILITY TO THE OTHER PARTY FOR
          SUCH TERMINATION. FOR THE SAKE OF CLARITY, ALL OBLIGATIONS WHICH
          AROSE PRIOR TO THIS EVENT SHALL STILL REMAIN WITH THE PARTIES.
          <br />
          <br />
          <br />
          <strong>25. VALIDITY</strong>
          <br />
          <br />
          THIS CONTRACT SHALL ENTER INTO FORCE WHEN DULY EXECUTED BY BOTH
          PARTIES AND SHALL REMAIN EFFECTIVE UNTIL THE FULL PERFORMANCE BY EACH
          PARTY OF ITS RESPECTIVE OBLIGATIONS HEREUNDER. ANY TERMINATION OF THE
          CONTRACT SHALL BE WITHOUT PREJUDICE TO THE RIGHTS AND OBLIGATIONS OF
          EACH PARTY AS ACCRUED AS OF THE DATE OF TERMINATION. <br />
          <br />
          <br />
          <strong>26. COMPLIANCE WITH MINIMUM STANDARDS</strong>
          <br />
          <br />
          PARTIES HEREBY REPRESENT AND WARRANT THAT THEY WILL AT ALL TIMES
          THROUGHOUT THE DURATION OF THIS AGREEMENT ADHERE, AT A MINIMUM, TO
          THE FOLLOWING ENVIRONMENTAL, HUMAN RIGHTS, AND HEALTH AND SAFETY
          STANDARDS:
          <br />
          <br />
          ENVIRONMENTAL STANDARDS: THE SOCIAL AND ENVIRONMENTAL STANDARDS
          ADOPTED BY THE UNITED NATIONS DEVELOPMENT PROGRAMMM (UNDP)
          <br />
          <br />
          HUMAN RIGHTS: THE EUROPEAN CONVENTION ON HUMAN RIGHTS AND ALL
          RELEVANT GUIDANCE AND PRECEDENTS.
          <br />
          <br />
          HEALTH AND SAFETY: THE INTERNATIONAL MINIMUM REQUIREMENTS FOR HEALTH
          PROTECTION IN THE WORKPLACE PUBLISHED BY THE WORLD HEALTH
          ORGANISATION (WHO).
          <br />
          <br />
          <br />
          <strong>SELLER </strong>
          <br />
          <br />
          VINCLASS OIL TRADING SA, <br />
          <br />
          14 RUE GRAND-PLACES, <br />
          <br />
          1700 FRIBOURG, SWITZERLAND <br />
          <br />
        </div>
      </div>
      <div className={styles.orderContainer__controlsContainer}>
        <Button link='/order/step-3'>
          <span className={styles.orderContainer__confirmButton}>
            {t('order:step2.submit button')}
          </span>
        </Button>
      </div>
    </section>
  );
}

export default OrderStep2;
